### ISSUE TITLE
Erweiterte Oberfläche zum Verwalten

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [AndiLeni/fonts#12]
Bestünde Intresse, eine Oberfläche zum Verwalten zu haben? Z.B. um Fonts auf Wunsch direkt ins Backend einzubinden oder auszuwählen, für welche Domain im Frontend sie integriert werden soll?

Oder auch, um sie zu löschen oder upzudaten.

**Comment by AndiLeni** [comment]
Das wäre sicherlich interessant. Vllt wäre eine Überprüfung, ob eine Schriftart bereits existiert auch gut. Aktuell wird alles überschrieben und die css `@import` wird einfach nochmal ergänzt 🤔

duplicate #5 und #4

**Comment by AWqxKAWERbXo** [comment]
Naja, die Frage war explizit, ob es dafür eine Oberfläche geben soll. Dann hätte ich sie beigesteuert. Aber wenn du es als Duplikat siehst, kann ja @iceman-fx passende Vorschläge in #4 und #5 erarbeiten.

**Comment by AndiLeni** [comment]
Ich mache das Issue gerne wieder auf, sie klangen für mich sehr ähnlich, aber ich schließe auch nicht aus, dass ich deinen Kernpunkt nicht ganz erfasst habe :)

**Comment by AWqxKAWERbXo** [comment]
Ich komme da leider aktuell nicht weiter dazu.
