### ISSUE TITLE
PHP8 Code aber kein min Version in package.yml gesetzt

### ISSUE THREAD

**Issue by bitshiftersgmbh** [AndiLeni/fonts#13]
Bei einem Kundenprojekt knallt es, weil das Probleme macht ...

```php
public static function getLicense(String $fontName): string|false
```

Das ist wohl PHP 8.x Notation. In der package.yml gibt es keine PHP-Bedingungen. Da müsste man sich in 1 Richtung entscheiden.

**Comment by AndiLeni** [comment]
Ja, das stimmt.
Man kann es in die package.yml setzen, aber am 28 Nov 2022 ist mit der 7.4 auch offiziell Schluss.

**Comment by AWqxKAWERbXo** [comment]
@bitshiftersgmbh die Zeit für das issue hätte man doch in einen PR investieren können

**Comment by bitshiftersgmbh** [comment]
> @bitshiftersgmbh die Zeit für das issue hätte man doch in einen PR investieren können

Ich setz meine Zeit ein, wie ich es möchte.

**Comment by AWqxKAWERbXo** [comment]
@bitshiftersgmbh jo, ich weiß, deine Zeit ist wertvoller als die der anderen. 😡

Ist btw. schon drin. https://github.com/AndiLeni/fonts/blob/5d3a959a777fd2167f133e379ca60d45ee98336d/package.yml#L17 

close plz
