### ISSUE TITLE
ist PHP8 zwingend notwendig?

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/fonts#19]
AddOn fonts konnte aus folgendem Grund nicht aktualisiert werden:
Die PHP-Version (7.4.30) entspricht nicht der geforderten Versionsbedingung ^8.0!

**Comment by AndiLeni** [comment]
7.4 ist hat sein EOL erreicht. 
Ich weiß nicht auswendig, ob wir PHP 8 features nutzen, aber es kommen bestimmt Type annotations oder ähnliche Sachen dazu in Zukunft.
