### ISSUE TITLE
Auch .woff installieren lassen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/fonts#2]
Wenn möglich, als 2. Font auch die .woff installieren lassen.

Beispiel:

@font-face {
    font-family: 'Open Sans';
    src: url('fonts/OpenSans-Light.woff2') format('woff2'),
        url('fonts/OpenSans-Light.woff') format('woff');
    font-weight: 300;
    font-style: normal;
    font-display: swap;
}

**Comment by AWqxKAWERbXo** [comment]
Halte ich für unnötig, siehe https://caniuse.com/woff2

**Comment by iceman-fx** [comment]
Für ältere Browser ist es aktuell schon noch notwendig.
Und der Aufwand sollte minimal sein, dies zu integrieren.

**Comment by AndiLeni** [comment]
Ich schließe das Issue hier mal.
Aktuell werden neben auch woff/woff2 auch noch andere Formate gespeichert.
Der Browser lädt sich dann ja die passendste herunter.
