### ISSUE TITLE
font-display: swap; als Option mit in die CSS-Generierung mit aufnehmen

### ISSUE THREAD

**Issue by iceman-fx** [AndiLeni/fonts#3]
Beispiel:

@font-face {
    font-family: 'Open Sans';
    src: url('fonts/OpenSans-Light.woff2') format('woff2'),
        url('fonts/OpenSans-Light.woff') format('woff');
    font-weight: 300;
    font-style: normal;
    font-display: swap;
}

**Comment by AWqxKAWERbXo** [comment]
Halte ich für sinnvoll, sollte sich dieses Addon jedoch weiterentwickeln und Icon-Fonts etc. laden können, dann wäre es wichtig, pro Schriftart festzulegen, ob man swap wünscht - oder nicht.

**Comment by danspringer** [comment]
Ist in https://github.com/AndiLeni/fonts/pull/11 enthalten.
