### ISSUE TITLE
REDAXO-eigene Methoden für Dateien nutzen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [AndiLeni/fonts#8]
https://github.com/AndiLeni/fonts/blob/29f87d533745e0751cbf5a16c71cc4fc748a2b50/pages/index.php#L45 u.a.

https://redaxo.org/doku/5.10/file#rexfile

Siehe auch #7

**Comment by AndiLeni** [comment]
Danke für die Pull Requests und die Issues :)
Sobald die Funktionalität passt, merge ich und nehme die vorgeschlagenen Änderungen vor.

**Comment by AWqxKAWERbXo** [comment]
Gerne. Da ich nicht mehr auf Slack erreichbar sein möchte, schreib mir gerne eine Mail, falls wir Mal zusammen das Thema Add-on Entwicklung für REDAXO anschauen sollen oder falls du dir in diesem Add-on Features wünschst. Ich biete dir da eine gute Stunde Zeit, wenn dich das weiter bringt.
